### ISSUE TITLE
'bytes' object has no attribute 'get_fields_and_field_types'

### ISSUE THREAD

**Issue by dustingooding** [mehmetkillioglu/ros2_message_converter#3]
When trying to convert a [DiagnosticStatus](https://github.com/ros2/common_interfaces/blob/foxy/diagnostic_msgs/msg/DiagnosticStatus.msg), there is a parsing failure when the `byte level` message member is reached.

```
Traceback (most recent call last):
  File "/root/colcon_ws/install/my_pkg/lib/my_pkg/subscriber", line 11, in <module>
    load_entry_point('my_pkg==0.1.0', 'console_scripts', 'subscriber')()
  File "/root/colcon_ws/install/my_pkg/lib/python3.8/site-packages/my_pkg/subscriber.py", line 60, in main
    rclpy.spin(my_pkg_subscriber)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/__init__.py", line 191, in spin
    executor.spin_once()
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/executors.py", line 714, in spin_once
    raise handler.exception()
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/task.py", line 239, in __call__
    self._handler.send(None)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/executors.py", line 429, in handler
    await call_coroutine(entity, arg)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/executors.py", line 354, in _execute_subscription
    await await_or_execute(sub.callback, msg)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/executors.py", line 118, in await_or_execute
    return callback(*args)
  File "/root/colcon_ws/install/my_pkg/lib/python3.8/site-packages/my_pkg/subscriber.py", line 51, in msg_callback
    self.fire_db.child(self.fire_child).update(message_converter.convert_ros_message_to_dictionary(msg))
  File "/root/colcon_ws/install/ros2_message_converter/lib/python3.8/site-packages/ros2_message_converter/message_converter.py", line 250, in convert_ros_message_to_dictionary
    dictionary[field_name] = _convert_from_ros_type(field_type, field_value)
  File "/root/colcon_ws/install/ros2_message_converter/lib/python3.8/site-packages/ros2_message_converter/message_converter.py", line 267, in _convert_from_ros_type
    field_value = _convert_from_ros_array(field_type, field_value)
  File "/root/colcon_ws/install/ros2_message_converter/lib/python3.8/site-packages/ros2_message_converter/message_converter.py", line 315, in _convert_from_ros_array
    return [_convert_from_ros_type(list_type, value) for value in field_value]
  File "/root/colcon_ws/install/ros2_message_converter/lib/python3.8/site-packages/ros2_message_converter/message_converter.py", line 315, in <listcomp>
    return [_convert_from_ros_type(list_type, value) for value in field_value]
  File "/root/colcon_ws/install/ros2_message_converter/lib/python3.8/site-packages/ros2_message_converter/message_converter.py", line 269, in _convert_from_ros_type
    field_value = convert_ros_message_to_dictionary(field_value)
  File "/root/colcon_ws/install/ros2_message_converter/lib/python3.8/site-packages/ros2_message_converter/message_converter.py", line 250, in convert_ros_message_to_dictionary
    dictionary[field_name] = _convert_from_ros_type(field_type, field_value)
  File "/root/colcon_ws/install/ros2_message_converter/lib/python3.8/site-packages/ros2_message_converter/message_converter.py", line 269, in _convert_from_ros_type
    field_value = convert_ros_message_to_dictionary(field_value)
  File "/root/colcon_ws/install/ros2_message_converter/lib/python3.8/site-packages/ros2_message_converter/message_converter.py", line 247, in convert_ros_message_to_dictionary
    message_fields = message.get_fields_and_field_types()
AttributeError: 'bytes' object has no attribute 'get_fields_and_field_types'
```

When I instrument the `_convert_from_ros_type()` method, it is indeed failing on the `byte` value.

```
[INFO] [1637960018.081069400] [vaporlink_subscriber]: Pushing new data: diagnostic_msgs.msg.DiagnosticArray(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=1637960017, nanosec=940142080), frame_id=''), status=[diagnostic_msgs.msg.DiagnosticStatus(level=b'\x00', name='foo', message='OK', hardware_id='foo', values=[diagnostic_msgs.msg.KeyValue(key='fizz:', value='1637960017.702749'), diagnostic_msgs.msg.KeyValue(key='buzz:', value='0.004085')])])

Field Type: std_msgs/Header
Field Value: std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=1637960017, nanosec=940142080), frame_id='')

Field Type: builtin_interfaces/Time
Field Value: builtin_interfaces.msg.Time(sec=1637960017, nanosec=940142080)

Field Type: string
Field Value:

Field Type: sequence<diagnostic_msgs/DiagnosticStatus>
Field Value: [diagnostic_msgs.msg.DiagnosticStatus(level=b'\x00', name='foo', message='OK', hardware_id='foo', values=[diagnostic_msgs.msg.KeyValue(key='fizz:', value='1637960017.702749'), diagnostic_msgs.msg.KeyValue(key='buzz:', value='0.004085')])]

Field Type: diagnostic_msgs/DiagnosticStatus
Field Value: diagnostic_msgs.msg.DiagnosticStatus(level=b'\x00', name='foo', message='OK', hardware_id='foo', values=[diagnostic_msgs.msg.KeyValue(key='fizz:', value='1637960017.702749'), diagnostic_msgs.msg.KeyValue(key='buzz:', value='0.004085')])

Field Type: octet
Field Value: b'\x00'

Traceback (most recent call last):
```

I suspect the issue is that `byte` in the msg gets converted to the `bytes` Python type, but `bytes` isn't handled in `_is_ros_binary_type()`.

**Comment by dustingooding** [comment]
Worth noting, I'm locally using a modification for parsing Time as described here: https://github.com/mehmetkillioglu/ros2_message_converter/issues/2#issuecomment-980363197

**Comment by dustingooding** [comment]
I suspect the resolution for this is:

```
def _is_ros_binary_type(field_type):
    """ Checks if the field is a binary array one, fixed size or not
    list(bytearray(de(encoded_data)))
    _is_ros_binary_type("uint8")
    >>> False
    _is_ros_binary_type("uint8[]")
    >>> True
    _is_ros_binary_type("uint8[3]")
    >>> True
    _is_ros_binary_type("char")
    >>> False
    _is_ros_binary_type("char[]")
    >>> True
    _is_ros_binary_type("char[3]")
    >>> True
    _is_ros_binary_type("octet")
    >>> True
    """
    return field_type.startswith('uint8[') or field_type.startswith('char[') or field_type.startswith('octet')
```

**Comment by dustingooding** [comment]
thanks!

**Comment by mehmetkillioglu** [comment]
Thank you for the PR. I am not actively maintaining this repository, so any PR is welcome at this point.
